# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

skpr_constraints_allowed <- function(points, level_pos, constraints_ir) {
    .Call(`_skpr_skpr_constraints_allowed`, points, level_pos, constraints_ir)
}

DOptimality <- function(currentDesign) {
    .Call(`_skpr_DOptimality`, currentDesign)
}

DOptimalityLog <- function(currentDesign) {
    .Call(`_skpr_DOptimalityLog`, currentDesign)
}

DOptimalityBlocked <- function(currentDesign, blockedVar) {
    .Call(`_skpr_DOptimalityBlocked`, currentDesign, blockedVar)
}

DOptimalityBlockedLog <- function(currentDesign, blockedVar) {
    .Call(`_skpr_DOptimalityBlockedLog`, currentDesign, blockedVar)
}

calculateDEfficiency <- function(currentDesign) {
    .Call(`_skpr_calculateDEfficiency`, currentDesign)
}

AOptimality <- function(currentDesign) {
    .Call(`_skpr_AOptimality`, currentDesign)
}

calculateAOptimalityPseudo <- function(currentDesign) {
    .Call(`_skpr_calculateAOptimalityPseudo`, currentDesign)
}

IOptimality <- function(currentDesign, momentsMatrix, blockedVar) {
    .Call(`_skpr_IOptimality`, currentDesign, momentsMatrix, blockedVar)
}

calcAliasTrace <- function(currentDesign, aliasMatrix) {
    .Call(`_skpr_calcAliasTrace`, currentDesign, aliasMatrix)
}

covarianceMatrixPseudo <- function(design) {
    .Call(`_skpr_covarianceMatrixPseudo`, design)
}

getPseudoInverse <- function(currentDesign) {
    .Call(`_skpr_getPseudoInverse`, currentDesign)
}

GEfficiency <- function(currentDesign, candset) {
    .Call(`_skpr_GEfficiency`, currentDesign, candset)
}

genOptimalDesign <- function(initialdesign, candidatelist, condition, momentsmatrix, initialRows, aliasdesign, aliascandidatelist, minDopt, tolerance, augmentedrows, kexchange) {
    .Call(`_skpr_genOptimalDesign`, initialdesign, candidatelist, condition, momentsmatrix, initialRows, aliasdesign, aliascandidatelist, minDopt, tolerance, augmentedrows, kexchange)
}

skpr_ce_select_rows_by_leverage <- function(design, inverse, kexchange, augmentedrows = 0L) {
    .Call(`_skpr_skpr_ce_select_rows_by_leverage`, design, inverse, kexchange, augmentedrows)
}

genOptimalDesignCoordinateExchangeConstrained <- function(points, factor_levels, modelmatrix_fn, coordinate_groups, constraints_ir = NULL, tolerance = 1e-4, kexchange = as.integer( c(NA_INTEGER)), augmentedrows = 0L, max_iter = 200L, recompute_every = 10L, repair_stuck_limit = 5L, repair_max_tries = 2000L, coordinate_group_max_candidates = 10000L) {
    .Call(`_skpr_genOptimalDesignCoordinateExchangeConstrained`, points, factor_levels, modelmatrix_fn, coordinate_groups, constraints_ir, tolerance, kexchange, augmentedrows, max_iter, recompute_every, repair_stuck_limit, repair_max_tries, coordinate_group_max_candidates)
}

genSplitPlotOptimalDesign <- function(initialdesign, candidatelist, blockeddesign, condition, momentsmatrix, initialRows, blockedVar, aliasdesign, aliascandidatelist, minDopt, interactions, disallowed, anydisallowed, tolerance, kexchange) {
    .Call(`_skpr_genSplitPlotOptimalDesign`, initialdesign, candidatelist, blockeddesign, condition, momentsmatrix, initialRows, blockedVar, aliasdesign, aliascandidatelist, minDopt, interactions, disallowed, anydisallowed, tolerance, kexchange)
}

genBlockedOptimalDesign <- function(initialdesign, candidatelist, condition, V, momentsmatrix, initialRows, aliasdesign, aliascandidatelist, minDopt, tolerance, augmentedrows, kexchange) {
    .Call(`_skpr_genBlockedOptimalDesign`, initialdesign, candidatelist, condition, V, momentsmatrix, initialRows, aliasdesign, aliascandidatelist, minDopt, tolerance, augmentedrows, kexchange)
}

