# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

AOptimality <- function(currentDesign) {
    .Call('skpr_AOptimality', PACKAGE = 'skpr', currentDesign)
}

DOptimality <- function(currentDesign) {
    .Call('skpr_DOptimality', PACKAGE = 'skpr', currentDesign)
}

IOptimality <- function(currentDesign, momentsMatrix) {
    .Call('skpr_IOptimality', PACKAGE = 'skpr', currentDesign, momentsMatrix)
}

genOptimalDesign <- function(initialdesign, candidatelist, condition, momentsmatrix, initialRows) {
    .Call('skpr_genOptimalDesign', PACKAGE = 'skpr', initialdesign, candidatelist, condition, momentsmatrix, initialRows)
}

